---
title: "Data Missingness Report"
output: html_notebook
---

```{r Setup, include=FALSE}
#setwd("~/Documents/DepenD Lab/NeuroMAP/NMAPReports/") #may need to change for each person running report

directory_onedriveH<-file.path("/Users/strength/OneDrive - The Pennsylvania State University/") #set personal directory
directory_onedriveW<-file.path("/Users/bbh5255/OneDrive - The Pennsylvania State University/") #set personal directory
directory_work<-file.path("/Users/bbh5255/Documents/DepenD Lab/NeuroMAP/NMAPReports/") #set directory
directory_home<-file.path("/Users/strength/Documents/DepenD Lab/NeuroMAP/NMAPReports/") #set directory

if (!require(easypackages)) {install.packages("easypackages"); library(easypackages) }
packages("readxl", "tidyverse", "dbplyr", "tidyr", "qualtRics", "lubridate", "dataCompareR", "kableExtra", "dataCompareR")

q_token <- "bigsHycE1tmf2sfK5HR2CKShxGPasXZqC2QZ2Gvl" #enter qualtrics API Token
qualtrics_api_credentials(api_key = q_token, 
                          base_url = "pennstate.ca1.qualtrics.com",
                          install = TRUE, overwrite = TRUE)

TodayDate <- today()
TodayPlus7 <-TodayDate +7

```

```{r Import Qualtrics Data, message=TRUE, include=FALSE}
surveys<-all_surveys()
S1Report <-fetch_survey(surveyID = "SV_23S2sjLm5Lmq7Ah", label = TRUE, verbose = TRUE, convert = FALSE, force_request = TRUE)
S2Report <-fetch_survey(surveyID = "SV_8jJlCrM3V7m0BoN", label = TRUE, verbose = TRUE, convert = FALSE, force_request = TRUE)
S3Report<-fetch_survey(surveyID = "SV_8ixbUxRgNWtxuHH", label=TRUE, verbose = TRUE, convert = FALSE, force_request = TRUE)
S4Report <-fetch_survey(surveyID = "SV_8tOIVRgh1T4D2g5",  label = TRUE, verbose = TRUE, convert = FALSE, force_request = TRUE) 

#convert date to ddtm readable format in R
S3Report$s3_sessioninfo_1<-lubridate::mdy(S3Report$s3_sessioninfo_1)
S4Report$s4_sessioninfo_1<-lubridate::mdy(S4Report$s4_sessioninfo_1)

```

```{r Clean S1Report Qualtrics Data}
S1Report<-S1Report %>%
  rename(
    
  )

```

```{r Clean Tracker Data}
Tracker <- read_xlsx(paste0(directory_onedriveH, "NEUROMAP Master V2.xlsx"), sheet = "Tracker")
Tracker$PHONE<-gsub("-", "", Tracker$PHONE)

ParticipantID <- Tracker %>%
  select(
    ID,
    PHONE,
    `STUDY PROGRESS`) %>%
  rename(Phone = PHONE) %>%
  drop_na() 
ParticipantID$Phone<-as.numeric(ParticipantID$Phone)

```

```{r Cleaning Acuity Scheduling Data, include=FALSE}
Acuity <-read_csv(paste0(directory_home, "Acuity Session Reports/schedule2020-02-26.csv"))
                    
LastWeek<-TodayDate - 7

#convert date time to readable format in R
Acuity$`Start Time (AM/PM)`<-format(strptime(Acuity$`Start Time`, format= '%m/%d/%y %H:%M'), "'%m/%d/%y '%I:%M:%S %p'") #convert time to am/pm from 24 hour clock
Acuity$`Start Time`<-lubridate::mdy_hm(Acuity$`Start Time`) #convert time to R friendly format
Acuity$`Session Date`<- date(Acuity$`Start Time`) # create date only variable for searching purposes

Acuity<-Acuity %>%
  mutate(
    `Type (Recode)`= case_when(
      .$`Type` == "Session 1" ~ "Session 1",
      .$`Type` == "Session 1 Follow Up (1.5 hours)" ~ "Session 1 FU",
      .$`Type` == "Session 1 Follow Up (30 minutes)" ~ "Session 1 FU",
      .$`Type` == "Session 1 Follow Up (3 hours)" ~ "Session 1 FU",
      .$`Type` == "Session 2 (Marissa)" ~ "Session 2",
      .$`Type` == "Session 2 (Mia)" ~ "Session 2",
      .$`Type` == "Session 2 (Austin)" ~ "Session 2",
      .$`Type` == "Session 2 (Grace)" ~ "Session 2",
      .$`Type` == "Session 2 (Chloe)" ~ "Session 2",
      .$`Type` == "Session 2 (Daniel and Begonia)" ~ "Session 2",
      .$`Type` == "Session 3 (1 hour follow-up)" ~ "Session 3 FU",
      .$`Type` == "Session 3 Follow-Up  (1.5 Hours)" ~"Session 3 FU",
      .$`Type` == "Session 3" ~ "Session 3",
      .$`Type` == "SONA Study 1" ~ "Other",
      .$`Type` == "RA Interviews" ~ "Other"))
```

```{r Create Dataframe With IDs, Sessions}

ParticipantData <- Acuity %>%
  select(-c(`Appointment Price`,
         `Amount Paid Online`,
         `Certificate Code`,
         `Date Scheduled`,
         `Label`,
         `Appointment ID`,
         `Notes`,
         `Paid?`,
         `Scheduled By`,
         `Start Time`,
         `End Time`
         )) %>%
  dplyr::filter(`Type (Recode)` != "Other") %>%
  #spread(key = `Type (Recode)`, value = `Session Date`) %>%
  #gather(
   # `Session 1 FU`)
  full_join(ParticipantID, by = "Phone")


ParticipantData <- ParticipantData[, c(11, 1, 2, 3, 4, 9, 8, 5, 10, 6, 7, 12)]
View(ParticipantData)
```

```{r Filter Current Weeks Session}

ParticipantData %>% 
  select(
    `ID`,
   # `First Name`,
   # `Last Name`,
    `Email`,
    `Canceled`,
    `Type`,
    `Session Date`) %>%
  filter(`Session Date`>= LastWeek & `Session Date`<= TodayDate) %>%
  arrange(`Session Date`) %>%
  kable(format = "html", escape = F, caption = "Record of Sessions")

```

```{r All Participants Marked In Progress Table, include=FALSE}
Tracker %>%
  select(
    `ID`,
    `NAME`,
    `ACTUAL GROUP`,
    `STUDY PROGRESS`,
    `NOTES ABOUT STATUS`,
    `EMAIL`
  ) %>%
  filter(`STUDY PROGRESS` == "IN PROG") %>%
  #full_join(Acuity, Tracker, by = `Email`) %>%
  kable(format = "html", escape = F, caption = "In Progress Participants")

```

```{r S4's in Next 7 Days}

Tracker %>%
  select(
    `ID`,
    `NAME`,
    `GENDER`,
    `AGE`,
    `ACTUAL GROUP`,
    `STUDY PROGRESS`,
    `NOTES ABOUT STATUS`,
    `EMAIL`,
    `S4 DATE`,
    `DAYS BETWEEN BASELINE AND S4`,
    `NOTES`
  ) %>%
  filter(`S4 DATE`>= TodayDate & `S4 DATE`<= TodayPlus7) %>%
  mutate(
   `MONTHS SINCE BASELINE` = `DAYS BETWEEN BASELINE AND S4`/ 30)
  #full_join(Acuity, Tracker, by = `Email`) %>%
  kable(format = "html", escape = F, caption = "S4's in Next 7 Days")
```
