
```{r dataCleaning, include=FALSE}

#directory for worksheet with participant data
ws_path <- "~/Documents/DepenD Lab/NeuroMAP/NMAPReports/weeklyStatusReport/data/rawData/NEUROMAP Master V2_Copy.xlsx"

#return the names of each sheet
neuroMAP_master<- ws_path %>% excel_sheets()

EnrollOverview <- read_excel(ws_path, sheet = "RO1 Aggregate")

#load master participant data worksheet
Master<- read_excel(ws_path, sheet = "MasterData")

#tidy up column names for Master

Master<-Master %>% 
  dplyr::rename(
    SCREEN_SENTDATE = "SCREEN: SENT DATE",
    SCREEN_COMPLETEDATE = "SCREEN: COMPLETE DATE", 
    SCREEN_COMPLETEYN = "SCREEN: COMPLETE Y/N", 
    INEL_CODE = "INELEGIBILITY CODE", 
    INEL_PHASE ="PHASE DEEMED INELIGIBLE", 
    INEL_YN = "ELIGIBLE YN",
    NAME = "Name")

#create record of start month and year for participants
Master$SCREEN_SENTDATE <- as.POSIXct(strptime(Master$SCREEN_SENTDATE, format = '%Y-%m-%d'))
Master$SCREEN_COMPLETEDATE <- as.POSIXct(strptime(Master$SCREEN_COMPLETEDATE, format = '%Y-%m-%d'))
#Master$S1_DATE <- as.POSIXct(strptime(Master$S1_DATE, format = '%Y-%m-%d'))

Master$SCREEN_SENT_MONTH <- format(Master$SCREEN_SENTDATE, '%m')
Master$SCREEN_SENT_YEAR <- format(Master$SCREEN_SENTDATE, '%Y')

Master$SCREEN_COMPLETE_MONTH <- format(Master$SCREEN_COMPLETEDATE, '%m')
Master$SCREEN_COMPLETE_YEAR <- format(Master$SCREEN_COMPLETEDATE, '%Y')

#Master$S1_MONTH <- format(Master$S1_DATE, '%m')
#Master$S1_YEAR <- format(Master$SCREEN_COMPLETEDATE, '%Y')

#factorize source
Master$SOURCE <- as.factor(Master$SOURCE)


#Master$STATUS <-factor(Master$STATUS, levels = c("Completed S2", "Completed screen", "Inquiry", "Invited S1", "No longer interested", "Scheduled S1", "Screen sent"))
levels(Master$STATUS)[levels(Master$STATUS)=="Screen sent"] <- "Screen Sent, Not Completed"
levels(Master$STATUS)[levels(Master$STATUS)=="Completed screen"] <- "Ineligible After Screen"

Master$SOURCE[is.na(Master$SOURCE)] <- "Unknown"

#establish path for Tracker file, load enrolled participant data
Tracker <-read_excel(ws_path, sheet = "Tracker")

Tracker <- Tracker %>%
#rename column names
  rename(
    R01_ENROLLMENT = "FMRI GROUP (Y/N)", 
    STATUS = "NOTES ABOUT STATUS") %>%
#create variable with participant status 
  mutate(`Status - Recode` = case_when(
    .$STATUS == "Scheduled S1" ~ "S1",
    .$STATUS == "Canceled S1" ~ "Not Enrolled",
    .$STATUS == "Scheduled S1 FU" ~ "S1",
    .$STATUS == "Completed S1" ~ "Stuck",
    .$STATUS == "Scheduled S2" ~ "S2",
    .$STATUS == "Completed S2" ~ "Stuck",
    .$STATUS == "Scheduled S3, Scheduled S4" ~ "S3/S4 Scheduled",
    .$STATUS == "Scheduled S3" ~ "S3",
    .$STATUS == "S3 Not Completed" ~ "Stuck",
    .$STATUS == "Completed S3" & .$R01_ENROLLMENT == "Y" ~ "Scan Needed",
    .$STATUS == "Completed S3" & .$R01_ENROLLMENT == "N" ~ "No fMRI - Completed T1",
    .$STATUS == "Scheduling S4" ~ "Scheduling",
    .$STATUS == "Invited S3" ~ "Scheduling",
    .$STATUS == "Ineligible" ~ "Ineligible",
    .$STATUS == "Non Responsive" ~ "MIA",
    .$STATUS == "Completed S4" ~ "fMRI - Completed T1",
    .$STATUS == "Non Responsive/Missed Session/Stuck" ~ "Stuck",
    .$STATUS == "Scheduled S4" ~ "S4",
    .$STATUS == "Scheduled S3, Completed S4" ~ "S3 Scheduled, S4 Completed",
    .$STATUS == "Excluded" ~ "Ineligible",
    .$STATUS == "Completed S3, Scheduled S4" ~ "S4",
    .$`STUDY PROGRESS` == "Mia" ~ "MIA"))
```

```{r Load Fonts, include=FALSE}
# lato chosen for good visability on small sreens. See https://medium.com/nightingale/choosing-a-font-for-your-data-visualization-2ed37afea637

showtext_auto()
font_add_google("Quicksand")
font_add_google("Lato", "lato")

```


```{r Import Session 3 Data, include=FALSE}
#save the directory location for session 3 xlsx
s3_path <- "~/Documents/DepenD Lab/NeuroMAP/NMAPReports/weeklyStatusReport/data/rawData/s3_quality_data.xlsx"

#get the names of all of the sheets contained in the s3_xlsx sheet for use with lapply
s3_names<-excel_sheets(s3_path)

#SPLIT and APPLY: generate list of dataframes containing contents of xlsx file
s3_sheet_list <- lapply(s3_names, function(x) read_excel(path = s3_path, sheet = x))

#add a new column with the corresponding name of each sheet so the data source can be identified when combined.
filelist <- mapply(cbind, s3_sheet_list, "Task_Label"=s3_names, SIMPLIFY=F)

#COMBINE: merge all list items into a single data frame as to make type usable for report generation. 

s3_all_data <- plyr::rbind.fill(filelist)

#



s3_all_data %>% filter(ID == 15)

```


```{r Data Cleaning for Mushroom Task, eval=FALSE, include=FALSE}
s3_shrooms$Date <- format(as.Date(s3_shrooms$Date, format = "%Y-%d-%m"), "%m-%d-%Y")
s3_shrooms$Researcher <- str_to_upper(s3_shrooms$Researcher)
```

