
```{r Overview Table, echo=FALSE}
#select the first worksheet in the vector to select the overview sheet
sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(),
      th(),
      th(),
      th(),
      th(colspan = 3, 'Vanilla Baseline'),
      th(colspan = 3, 'Defend the Kingdom'),
      th(colspan = 3, 'Sorting Mushrooms'),
      th(colspan = 3, 'Neighborhood'),
      th(colspan = 3, 'Vending Machine')
    ),
    tr(
      th('Date'),
      th('ID'),
      th('RA'),
      th('Overall'),
      lapply(rep(c('P', 'ET', 'B'), 5), th)
    )
  )
))
#print(sketch)

S3_Overview<- s3_all_data %>% filter(Task_Label == "S3_Overview") %>%
  select(-Task_Label) %>%
  arrange(ID) %>%
  mutate(duplicate = duplicated(.$ID))

duplicated(S3_Overview$ID)

datatable(S3_Overview, container = sketch, rownames = FALSE) %>%
  formatStyle(
  'duplicate',
  target = 'row',
  backgroundColor = styleEqual(c(TRUE, FALSE), c('red', 'white'))
)



#s3_overview %>% select()
#s3_shrooms$DateReformated <- format(s3_shrooms$Date, format = "%m-%d-%Y")
#s3_shrooms$DateReformated <- as.POSIXct(s3_shrooms$DateReformated, format = "%m-%d-%Y")
```


```{r Calculate Average Rating Each Week, , echo=FALSE}
#create a new variable to be used for grouping time-points
S3_Overview$week_num <-strftime(S3_Overview$Date, format = "%V")

#data cleaning
S3_Overview$Overall <- as.numeric(S3_Overview$Overall)

#figure out the average score for each week
S3_Overview_avg_rating<-S3_Overview %>% select(Date, Overall, week_num) %>% na.omit() %>% filter(Overall != "NA") %>%
  group_by(week_num) %>%
  summarize(average_score = mean(Overall))

#from the weekly average determine the average score overall
mean<-transmute(S3_Overview_avg_rating, average = mean(average_score))
mean <- mean[1,1]

S3_Overview_avg_rating %>% ggplot(aes(x = week_num, y = average_score, group = 1)) +
  geom_line() +
  geom_hline(yintercept = 3.44, color = "red")
  scale_y_continuous(limits = c(0,5)) +
    labs(title = "The Average Score Given By Experimenters to Rate Session 3 Data Collection")



```


